services:
  - type: web
    name: pdf-to-word-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: CORS_ALLOW_ALL
        value: "true"
    plan: free 